### ISSUE TITLE
Request firmware failed with error 0xfffffffe on TinkerOS v2.0.7

### ISSUE THREAD

**Issue by samsonluk** [Miouyouyou/RockMyy-Build#2]
Just replaced this kernel with TinkerOS v2.0.7's  4.4.103 but received the above error, any idea where to obtain the required firmware?
# uname -a
Linux tinkerboard 4.15.0-rc9-Kernel-Maker-XV #1 SMP PREEMPT Mon Jan 22 19:59:37 CET 2018 armv7l GNU/Linux

rtl8723bs: acquire FW from file:rtlwifi/rtl8723bs_nic.bin
rtl8723bs mmc1:0001:1: Direct firmware load for rtlwifi/rtl8723bs_nic.bin failed with error -2
Request firmware failed with error 0xfffffffe

**Comment by Miouyouyou** [comment]
Error -2 means `File not found` (ENOENT).

I might have forgotten to put the firmware file in `/lib/firmware` I guess.
So, instead, you might want to get this file : https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/rtlwifi/rtl8723bs_nic.bin and put into `/lib/firmware/rtlwifi/` and then reload the driver or reboot.

Create the `rtlwifi` folder if not present.

**Comment by samsonluk** [comment]
Ok, fixed.  Many thanks!

**Comment by Miouyouyou** [comment]
Great !
